name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: patiberzin-dev
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      - name: Commit e push
        uses: EndBug/add-and-commit@v9
        with:
          message: "update snake"
          add: "dist/*.svg"
