# new

name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: patiberzin-dev
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
